name: Actualización - BCRA

on:
  schedule:
    - cron: '42 16 * * *'  # 13:42 ARG = 16:42 UTC
  workflow_dispatch:

jobs:
  bcra:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script BCRA
        run: ./main_bcra.bat
